language: php
php:
 - '7.1'

sudo: true

addons:
  ssh_known_hosts:
    - www.cnwangjie.com
    - axy-api.cnwangjie.com

services:
 - mysql

before_install:
 - mysql -e 'CREATE DATABASE axym;'
 - sed -i "s/https:\/\/github.com\/cnwangjie/https:\/\/$GITHUB_PUBLICREPO_TOKEN@github.com\/cnwangjie/" composer.json


install:
 - composer install
 - cp .env.example .env
 - php artisan key:generate
 - php artisan jwt:secret
 - php artisan migrate
 - php artisan db:seed

script:
 - ./vendor/bin/phpunit -v --debug

after_success:
 - sudo apt-get update
 - sudo apt-get install sshpass
 - npm install apidoc --global
 - apidoc
 - sshpass -p $DOC_UPLOAD_PASSWORD scp ./doc/api_data.js root@www.cnwangjie.com:/var/www/html/axy-api-doc/api_data.js

defore_deploy:
  - echo "$DEPLOY_KEY" > key.pem
  - chmod 600 key.pem

deploy:
  - provider: script
    script: sshpass -p '' -P passphrase ssh -i key.pem root@axy-api.cnwangjie.com '/root/deploy.sh'
    on:
      branch: api-dev
